---
- name: "Build Docker images with Ansible"
  hosts: app_servers
  become: true
  vars:
    docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
    docker_password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
    build_number: "{{ build_number }}"  # Use the build_number variable

  tasks:
    - name: Clone repo
      command: git clone https://github.com/abohmeed/theweatherapp.git
      args:
        chdir: /home/ubuntu
      ignore_errors: yes

    - name: Log in to Docker
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Build Docker images from docker-compose
      shell: |
        docker-compose -f /home/ubuntu/theweatherapp/docker-compose.yaml build
      args:
        chdir: /home/ubuntu/theweatherapp
      ignore_errors: yes

    - name: Tag and push Docker images
      shell: |
        docker compose up -d      
        docker tag theweatherapp_weather:latest sharara99/weather:{{ build_number }}
        docker tag theweatherapp_auth:latest sharara99/auth:{{ build_number }}
        docker tag theweatherapp_ui:latest sharara99/ui:{{ build_number }}
        docker tag mysql:latest sharara99/db:{{ build_number }}
        docker push sharara99/weather:{{ build_number }}
        docker push sharara99/auth:{{ build_number }}
        docker push sharara99/ui:{{ build_number }}
        docker push sharara99/db:{{ build_number }}
      args:
        chdir: /home/ubuntu/theweatherapp
      ignore_errors: yes
