apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: weatherapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sharara99/auth:latest
          ports:
            - containerPort: 8081
