apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db
  namespace: weatherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: auth
        image: sharara99/auth:latest
        env:
        - name: DB_HOST
          value: "localhost"  # db is now in the same pod
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "my-secret-pw"
        - name: DB_NAME
          value: "my_database"
        ports:
        - containerPort: 8080
      - name: db
        image: sharara99/db:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "my-secret-pw"
        ports:
        - containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: weatherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: sharara99/ui:latest # Replace with your actual image
        env:
        - name: AUTH_HOST
          value: "auth-db"  # Updated to reflect combined auth-db pod
        - name: AUTH_PORT
          value: "8080"
        - name: WEATHER_HOST
          value: "weather"
        - name: WEATHER_PORT
          value: "5000"
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: weatherapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: sharara99/weather:latest # Replace with your actual image
        env:
        - name: APIKEY
          value: "6d92c50bdamsh81137f3b87ace1fp1d53eejsnfe818b9dbc83"
