apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-app
  namespace: to-do-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
      - name: to-do-app
        image: sharara99/to-do-list:latest  
        ports:
          - containerPort: 3000