apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: weatherapp
spec:
  selector:
    app: auth
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: weatherapp
spec:
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001 # Specify a NodePort within the range 30000-32767
  type: NodePort # Expose the UI outside of the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: weather
  namespace: weatherapp
spec:
  selector:
    app: weather
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: weatherapp
spec:
  selector:
    app: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306