apiVersion: v1
kind: Service
metadata:
  name: weather
  namespace: weatherapp
spec:
  type: NodePort
  selector:
    app: weather
  ports:
    - port: 8080           # Port that the service listens on
      targetPort: 8080     # Port on the pod to forward traffic to
      nodePort: 30080      # Static port on each node (can be assigned dynamically)
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: weatherapp
spec:
  type: NodePort
  selector:
    app: auth
  ports:
    - port: 8081           # Port that the service listens on
      targetPort: 8081     # Port on the pod to forward traffic to
      nodePort: 30081      # Static port on each node (can be assigned dynamically)
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: weatherapp
spec:
  type: NodePort
  selector:
    app: ui
  ports:
    - port: 80             # Port that the service listens on
      targetPort: 80       # Port on the pod to forward traffic to
      nodePort: 30082      # Static port on each node (can be assigned dynamically)
