apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: weatherapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: sharara99/ui:latest
          ports:
            - containerPort: 80
