apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
  namespace: weatherapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: sharara99/weather:latest
          ports:
            - containerPort: 8080
