apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: to-do-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sharara99/to-do-app.git
    targetRevision: HEAD
    path: k8s/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: to-do-app
  syncPolicy: 
    syncOptions: 
      - CreateNamespace=true
    automated: 
      selfHeal: true 
      prune: true
