# Number of replicas for your to-do-app
replicaCount: 4  

# Container image details for the to-do-app
image:
  repository: sharara99/to-do-app  # Your image repository
  pullPolicy: IfNotPresent           # Image pull policy
  tag: "latest"                      # Image tag

# Image pull secrets (if you use a private registry)
imagePullSecrets: []

# Helm chart name overrides
nameOverride: ""
fullnameOverride: ""

# Service Account configuration
serviceAccount:
  create: true  # If true, a ServiceAccount will be created
  automount: true
  annotations: {}
  name: ""      # Leave blank to auto-generate service account name

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Pod security context
podSecurityContext: {}
securityContext: {}

# Service configuration for to-do-app
service:
  type: NodePort   # Changed to NodePort for accessibility
  port: 3000       # The port for the service

# Ingress configuration (if needed, enable this section)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Resource requests and limits for to-do-app (adjust as needed)
resources: {}
  # Uncomment and adjust as needed
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Liveness and readiness probes for to-do-app
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Autoscaling settings (you can enable if needed)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Volumes and VolumeMounts (if any)
volumes: []
volumeMounts: []

# NodeSelector, tolerations, and affinity for scheduling
nodeSelector: {}
tolerations: []
affinity: {}

# Pramithous configuration
pramithous:
  enabled: true
  image:
    repository: pramithous/pramithous  # Official Pramithous image
    tag: latest  # Specify version if needed
  service:
    enabled: true
    port: 8080

# Grafana configuration
grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: latest  # Specify version if needed
  service:
    enabled: true
    port: 3000
