apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.grafana.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana-container
        image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
        ports:
          - containerPort: {{ .Values.grafana.service.port }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.grafana.service.port }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.grafana.service.port }}
