apiVersion: v1
kind: Service
metadata:
  name: grafana-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.port }}
  selector:
    app: grafana
